### ISSUE TITLE
Coursera Johns Hopkins Specialization in Data Science course dependency information

### ISSUE THREAD

**Issue by huei90** [huei90/Knowledge-Database#9]
Link：https://d396qusza40orc.cloudfront.net/rprog/doc/JHDSS_CourseDependencies.pdf

From：Coursera

Agenda:

- [ ] The Data Scientist’s Toolbox
- [ ] R Programming 
- [ ] Getting and Cleaning Data 
- [ ] Exploratory Data Analysis 
- [ ] Reproducible Research 
- [ ] Statistical Inference 
- [ ] Regression Models 
- [ ] Practical Machine Learning 
- [ ] Developing Data Products

Just a short remind note for me.

**Comment by Marcellomaremonti** [comment]
hi!

**Comment by huei90** [comment]
Hi @Marcellomaremonti How are you!

**Comment by Marcellomaremonti** [comment]
I am good thanks @huei90!

**Comment by huei90** [comment]
failed failed failed =(
